W7/D2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]
  resources :bands do
    resources :albums
  end
  resources :albums do 
    resources :tracks
  end
end

W7/D2/music_app/app/models/album.rb
class Album < ApplicationRecord
    validates :title, :year, :studio, presence: true,
  
    belong_to :band,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: :Band




end

W7/D2/music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: :Album
        
end

W7/D2/music_app/app/models/track.rb
class Track < ApplicationRecord
    
end

W7/D2/music_app/app/models/user.rb
class User < ApplicationRecord
    validates :email, :session_token, presence: true
    validates :password_digest, presence: { message: 'Password can\'t be blank' }
    validates :email, uniqueness: true

    attr_reader :password

    after_initialize :ensure_session_token

    def self.find_by_credentials(email, password)
        user = User.find_by(username: username)
        return user if user && user.is_valid_password?(password)
        nil   
    end

    def self.generate_session_token
        SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        #In #password= use self.password_digest=. (
        #self.___= calls a setter method defined for us by ActiveRecord, which is the state that is saved by self.save.
        #While @___ makes a new instance variable, unrelated to self.save)
        self.password_digest = Bcrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        Bcrypt::Password.new(self.password_digest).is_password?(password)
    end
end

W7/D2/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        @bands = Album.all
        render :index
    end
    
    def show
        @album = Album.find(params[:id])
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.save!
            redirect_to band_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find(params[:id])
        render :edit
    end

    def update
        @album = Album.find(params[:id])
        if @album.update_attributes(album_params)
            redirect_to album_url
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    private
    
    def album_params
        params.require(:album).permit(:title, :year, :studio)
    end
end

W7/D2/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def log_in_user!(user)
        session[:session_token] = user.reset_session_token!
    end
end

W7/D2/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end
    
    def show
        @band = Band.find(params[:id])
        render :new
    end

    def create
        @band = Band.new(band_params)
        if @band.save!
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find(params[:id])
        if @band.update_attributes(band_params)
            redirect_to band_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    private
    
    def band_params
        params.require(:band).permit(:name)
    end
end

W7/D2/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login(@user)
            redirect_to user.url(@user)
        else
            flash.now[:errors] = ["Invalid Username or Password"]
            render :new
        end
    end

    def destroy
        
    end
end

W7/D2/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

W7/D2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_current_user!, except: [:create, :new]

    def new
        @users = User.all
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def user_params
        params.require(:user).permit(:username, :email, :age, :password)
    end
            

end

W7/D2/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W7/D2/music_app/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        return '<input type="hidden" name="authenticity_token" value=:<%= form_authencity_token %>"/>'.html_safe
end

W7/D2/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W7/D2/music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

W7/D2/music_app/app/views/albums/_album.html.erb
<% if action == :show %>
  <a href="<%= albums_url %>"> <!-- users_url = "/users" : RAILS auto generated url helper METHOD -->
    Albums Index
  </a>
<% elsif action == :index %>
  <a href="<%= album_url(album) %>">
    <%= album.title %>'s playlist
  </a>
<% end %>

<ul>
  <li><%= album.title %></li>
  <li><%= album.year %></li>
  <li><%= album_type ? "Studio" : "Live" %></li>
  <li>
    <a href="<%= edit_album_url(album) %>">Edit Album</a>
  </li>
  <li>
    <form action="<%= album_url(album) %>" method="POST" >
      <%= auth_token %>
      <input type="hidden" name="_method" value="DELETE"/>
      <input type="submit" value="Delete Album" />
    </form>
  </li>
</ul>

W7/D2/music_app/app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : album_url) %>
<% method = (album.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token %>

  <label for="title">Name</label>
  <input
    type="text"
    name="album[title]"
    id="title"
    value="<%= album.title %>">

  <br>

  <label for="album_year">Released Year</label>
  <input
    type="integer"
    name="album[integer]"
    id="album_year"
    value="<%= album.year %>">
  <br>

  <input
    type="radio"
    name="album[studio]"
    value="Studio"
    id="album_type"
    <%= album.studio ? "checked" : "" %>>
  <label for="album_type">Studio</label>
  <input
    type="radio"
    name="album[studio]"
    value="Live"
    id="album_type"
    <%= !album.studio ? "checked" : "" %>>
  <label for="album_type">Live</label>
  <br>

  <br>
  <% submit_text = (album.persisted? ? 'Update' : 'Create') + ' album!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

W7/D2/music_app/app/views/albums/edit.html.erb
<% render "form", album: @album, action: :edit%>

W7/D2/music_app/app/views/albums/index.html.erb
<h1>Here are all the albums:</h1>

<a href="<%= new_album_url %>">
    New Album
</a>

<ul>
    <% @albums.each do |album| %>
        <li>
            <%= render "album", album: album, action: :index %>
        </li>
    <% end %>
</ul>

W7/D2/music_app/app/views/albums/new.html.erb
<%= render "form", album: @album, action: :new %>

W7/D2/music_app/app/views/albums/show.html.erb
<%= render "album", album: @album, action: :show %>

<h3><%= @albums.username %>'s Activity</h3>
<ul>
    <% @albums.tracks.each do |track|%>
        <li>
            <%= track %>
        </li>
    <% end %>
</ul>